-- INTERSECT ALL keeps duplicate matches from LHS
-- setup:
CREATE TABLE t1 (id INT);
INSERT INTO t1 VALUES (1);
INSERT INTO t1 VALUES (2);
INSERT INTO t1 VALUES (2);
INSERT INTO t1 VALUES (3);
CREATE TABLE t2 (id INT);
INSERT INTO t2 VALUES (2);
INSERT INTO t2 VALUES (3);
INSERT INTO t2 VALUES (4);
-- input:
SELECT id FROM t1 INTERSECT ALL SELECT id FROM t2;
-- expected output:
2
3
-- expected status: 0
